id: A82A92FBC
base_file: fF684.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:15:53.720004
  last_modified_at: 2022-05-30 22:15:53.720022
